name: main

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: gcc main.c
        
      - name: Test
        run: ./a.out
        
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: ./a.out

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download Binary
        uses: actions/download-artifact@v4
        with:
          name: binary
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: a.out
