name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: gcc main.c
      - name: Test
        run: ./a.out
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: a.out
